[dc]
192.168.1.101  # Η IP του Windows Server σου

[dc:vars]
ansible_winrm_operation_timeout_sec=60
ansible_winrm_read_timeout_sec=70
ansible_port=5985
ansible_user=Administrator
ansible_password=Peugeot308gt!
ansible_connection=winrm
ansible_winrm_server_cert_validation=ignore
ansible_winrm_scheme=http
